import {adminTests} from './admin-content.js';

const T='public/thumbnails/';
export const baseTests = [
  {id:'methods-sem2-tf-2026',title:'Methods Semester 2 Examination - Tech Free',subject:'Mathematical Methods',units:'1 & 2',course:'methods-12',topics:['Algebra','Functions','Calculus'],difficulty:'Advanced',tech:'Tech-free',year:2026,reading:10,minutes:60,marks:50,questions:10,file:'public/resources/methods-12/tests/methods-sem2-tech-free-2026.pdf',solutionFile:null,thumbnail:T+'methods-12-test.svg',description:'Semester 2 Mathematical Methods tech-free examination.',dateAdded:'2026-10-01'},
  {id:'differential-calculus-2026',title:'Differential Calculus - Spider-Man',subject:'Mathematical Methods',units:'1 & 2',course:'methods-12',topics:['Differentiation','Applications of Calculus'],difficulty:'Advanced',tech:'Tech-free',year:2026,reading:5,minutes:50,marks:32,questions:3,file:'public/resources/methods-12/tests/differential-calculus-2026.pdf',solutionFile:null,thumbnail:T+'methods-12-test.svg',description:'Differential calculus assessment with differentiation, stationary points and graph analysis.',dateAdded:'2026-10-01'},
  {id:'circular-functions-tf-2026',title:'Circular Functions - The Backrooms',subject:'Mathematical Methods',units:'1 & 2',course:'methods-12',topics:['Circular Functions','Trigonometry'],difficulty:'Advanced',tech:'Tech-free',year:2026,reading:5,minutes:45,marks:31,questions:6,file:'public/resources/methods-12/tests/circular-functions-tech-free-2026.pdf',solutionFile:null,thumbnail:T+'methods-12-test.svg',description:'Tech-free circular functions assessment.',dateAdded:'2026-10-01'},
  {id:'circular-functions-ta-2026',title:'Circular Functions - The Hail Mary Manoeuvre',subject:'Mathematical Methods',units:'1 & 2',course:'methods-12',topics:['Circular Functions','Trigonometry'],difficulty:'Advanced',tech:'Technology active',year:2026,reading:5,minutes:45,marks:30,questions:3,file:'public/resources/methods-12/tests/circular-functions-tech-active-2026.pdf',solutionFile:null,thumbnail:T+'methods-12-test.svg',description:'Technology-active circular functions assessment.',dateAdded:'2026-10-01'},

  {id:'methods-sac2-2026',title:'Application Task 2 - The Elementary Integral',subject:'Mathematical Methods',units:'3 & 4',course:'methods-34',topics:['Integration','Applications of Calculus'],difficulty:'Separator',tech:'CAS permitted',year:2026,reading:15,minutes:120,marks:null,questions:8,file:'public/resources/methods-34/tests/sac2-2026.pdf',solutionFile:null,thumbnail:T+'methods-34-test.svg',description:'Mathematical Methods 3/4 Application Task 2.',dateAdded:'2026-10-01'},
  {id:'methods-sac3-2026',title:'Application Task 3 - The Chairs Club Dating Game',subject:'Mathematical Methods',units:'3 & 4',course:'methods-34',topics:['Probability','Statistics'],difficulty:'Separator',tech:'CAS permitted',year:2026,reading:15,minutes:120,marks:null,questions:null,file:'public/resources/methods-34/tests/sac3-2026.pdf',solutionFile:null,thumbnail:T+'methods-34-test.svg',description:'Mathematical Methods 3/4 Application Task 3.',dateAdded:'2026-10-01'},
  {id:'ip-redemption-3-modified',title:'IP Redemption Task 3 - Modified',subject:'Mathematical Methods',units:'3 & 4',course:'methods-34',topics:['Applications of Calculus'],difficulty:'Separator',tech:'CAS permitted',year:2026,reading:15,minutes:120,marks:null,questions:8,file:'public/resources/methods-34/tests/ip-redemption-task-3-modified.pdf',solutionFile:null,thumbnail:T+'methods-34-test.svg',description:'Modified Mathematical Methods 3/4 application task.',dateAdded:'2026-10-01'},
  {id:'ip-redemption-3-original',title:'IP Redemption Task 3 - Original',subject:'Mathematical Methods',units:'3 & 4',course:'methods-34',topics:['Applications of Calculus'],difficulty:'Separator',tech:'CAS permitted',year:2026,reading:15,minutes:120,marks:null,questions:10,file:'public/resources/methods-34/tests/ip-redemption-task-3-original.pdf',solutionFile:null,thumbnail:T+'methods-34-test.svg',description:'Original Mathematical Methods 3/4 application task.',dateAdded:'2026-10-01'},
  {id:'ip-redemption-3-part-1',title:'IP Redemption Task 3 - Part 1',subject:'Mathematical Methods',units:'3 & 4',course:'methods-34',topics:['Applications of Calculus'],difficulty:'Separator',tech:'CAS permitted',year:2026,reading:15,minutes:120,marks:78,questions:5,file:'public/resources/methods-34/tests/ip-redemption-task-3-part-1.pdf',solutionFile:null,thumbnail:T+'methods-34-test.svg',description:'Part 1 of the Mathematical Methods 3/4 IP Redemption application task.',dateAdded:'2026-10-01'},

  {id:'kinematics-2026',title:"Kinematics - Felix's Party Quiz Showdown",subject:'Specialist Mathematics',units:'1 & 2',course:'specialist-12',topics:['Kinematics'],difficulty:'Advanced',tech:'Tech-free',year:2026,reading:5,minutes:50,marks:25,questions:5,file:'public/resources/specialist-12/tests/kinematics-2026.pdf',solutionFile:'public/resources/specialist-12/solutions/kinematics-2026-solutions.pdf',thumbnail:T+'specialist-12-test.svg',description:'Position, velocity, acceleration, displacement and total-distance kinematics assessment.',dateAdded:'2026-10-01'},
  {id:'matrices-2026',title:'Matrices - Golden Boot Protocol',subject:'Specialist Mathematics',units:'1 & 2',course:'specialist-12',topics:['Matrices'],difficulty:'Advanced',tech:'Scientific calculator',year:2026,reading:5,minutes:60,marks:40,questions:6,file:'public/resources/specialist-12/tests/matrices-2026.pdf',solutionFile:'public/resources/specialist-12/solutions/matrices-2026-solutions.pdf',thumbnail:T+'specialist-12-test.svg',description:'Matrices assessment covering operations, determinants, inverses and systems.',dateAdded:'2026-10-01'},
  {id:'further-trig-2026',title:"Further Trigonometry - Selby's Casting Crisis",subject:'Specialist Mathematics',units:'1 & 2',course:'specialist-12',topics:['Further Trigonometry'],difficulty:'Advanced',tech:'Tech-free',year:2026,reading:5,minutes:55,marks:33,questions:6,file:'public/resources/specialist-12/tests/further-trigonometry-2026.pdf',solutionFile:'public/resources/specialist-12/solutions/further-trigonometry-2026-solutions.pdf',thumbnail:T+'specialist-12-test.svg',description:'Further trigonometry assessment with identities, equations and inverse trigonometry.',dateAdded:'2026-10-01'},
  {id:'complex-numbers-2026',title:'Complex Numbers',subject:'Specialist Mathematics',units:'1 & 2',course:'specialist-12',topics:['Complex Numbers'],difficulty:'Advanced',tech:'Tech-free',year:2026,reading:5,minutes:45,marks:30,questions:4,file:'public/resources/specialist-12/tests/complex-numbers-2026.pdf',solutionFile:'public/resources/specialist-12/solutions/complex-numbers-2026-solutions.pdf',thumbnail:T+'specialist-12-test.svg',description:'Complex numbers assessment. The marking guide flags the defective printed Question 1.',dateAdded:'2026-10-01'},

  {id:'physics-motion-2026',title:'Physics Motion - Peppa Pig',subject:'Physics',units:'1 & 2',course:'physics-12',topics:['Motion','Kinematics'],difficulty:'Advanced',tech:'Scientific calculator',year:2026,reading:5,minutes:45,marks:51,questions:6,file:'public/resources/physics-12/tests/motion-2026.pdf',solutionFile:'public/resources/physics-12/solutions/motion-2026-solutions.pdf',thumbnail:T+'physics-12-test.svg',description:'Physics Unit 2 motion problem-solving assessment.',dateAdded:'2026-10-01'},
  {id:'partial-fraction-bee-2026',title:'Partial Fraction Bee',subject:'Other',units:'',course:'other',topics:['Partial Fractions'],difficulty:'Separator',tech:'Tech-free',year:2026,reading:0,minutes:60,marks:63,questions:6,file:'public/resources/other/tests/partial-fraction-bee-2026.pdf',solutionFile:null,thumbnail:T+'other-test.svg',description:'A 63-mark Partial Fraction Bee challenge paper.',dateAdded:'2026-10-01'}
];
export const tests = [...baseTests,...adminTests];
export const testById = id => tests.find(t=>t.id===id);
