import {courses,courseById} from './data/courses.js';
import {lessons,lessonById,lessonsForCourse,lessonsForTopic} from './data/lessons.js';
import {practiceQuestions,dailyQuestions,questionById} from './data/questions.js';
import {tests,testById} from './data/tests.js';
import {resources} from './data/resources.js';
import {WHATS_NEW,SITE} from './data/site.js';
import {load,levelForXp} from './progress/store.js';
import {pageHead,courseCard,questionCard,testCard,resourceCard,tag,progressBar,emptyState} from './components.js';
import {renderMathString,dailyIndex,courseMastery,topicMastery,fmtDate,searchEverything,esc} from './utils.js';

const sectionTitle=(eyebrow,title,desc='',right='')=>`<div class="section-title"><div><div class="eyebrow dark">${eyebrow}</div><h2>${title}</h2>${desc?`<p>${desc}</p>`:''}</div>${right}</div>`;

export function homePage(){
  const p=load(); const level=levelForXp(p.xp); const daily=dailyQuestions[dailyIndex(dailyQuestions.length)];
  const next=lessons.find(l=>!p.completedLessons.includes(l.id))||lessons[0];
  return `<section class="hero"><div class="hero-copy"><div class="eyebrow">VCE MATHEMATICS, BUILT DIFFERENT</div><h1>Master mathematics.<br><em>Not just the exam.</em></h1><p>Interactive Methods and Specialist courses, serious practice, free Brainpower assessments and a resource library - all connected in one place.</p><div class="hero-actions"><a class="btn primary large" href="#lesson/${next.id}">Continue learning →</a><a class="btn light large" href="#tests">Find a practice test</a></div><div class="hero-mini"><span>✓ No paywall</span><span>✓ No AI required</span><span>✓ Progress saved locally</span></div></div>
  <div class="hero-visual"><div class="roadmap-card"><div class="roadmap-header"><div><small>YOUR NEXT PATH</small><h3>${courseById(next.course).short}</h3></div><span class="level-pill">LVL ${level}</span></div><div class="roadmap"><div class="road-node done"><span>✓</span><div><b>Foundation</b><small>Core skills</small></div></div><div class="road-line"></div><div class="road-node current"><span>∫</span><div><b>${next.title}</b><small>${next.minutes} min • ${next.difficulty}</small></div><a href="#lesson/${next.id}">→</a></div><div class="road-line"></div><div class="road-node locked"><span>◇</span><div><b>Checkpoint</b><small>Unlock by progressing</small></div></div></div></div><div class="floating-math a">∫</div><div class="floating-math b">i</div><div class="floating-math c">Σ</div></div></section>
  <section class="quick-stats"><div><strong>${p.xp}</strong><span>XP earned</span></div><div><strong>${p.completedLessons.length}</strong><span>Lessons mastered</span></div><div><strong>${p.correctQuestions.length}</strong><span>Questions solved</span></div><div><strong>${p.streak}</strong><span>Day streak</span></div></section>
  <section class="section">${sectionTitle('LEARN','Choose your course','Start from the beginning or jump directly to the topic you need.')}<div class="course-grid">${courses.map(c=>courseCard(c,p)).join('')}</div></section>
  <section class="section soft"><div class="daily-layout"><div>${sectionTitle('DAILY BRAINPOWER','One problem. Every day.','A rotating pre-built challenge. No generated questions.')}${questionCard(daily)}</div><aside class="daily-side card"><div class="eyebrow dark">WHY BRAINPOWER?</div><h3>Everything talks to everything.</h3><ul class="check-list"><li>Lessons link to practice.</li><li>Practice links to tests.</li><li>Test results stay in your dashboard.</li><li>Resources are searchable by course and topic.</li><li>Arcade games are optional, because sometimes you need a break.</li></ul><a class="text-link" href="#about">How the platform works →</a></aside></div></section>
  <section class="section">${sectionTitle('TEST CENTRE','Real Brainpower assessments','Preview, download or sit a test in Exam Mode.',`<a class="btn ghost" href="#tests">Browse all tests →</a>`)}<div>${tests.map(testCard).join('')}</div></section>
  <section class="section dark-section">${sectionTitle('WHAT\'S NEW','Recently at Brainpower','The platform is built to grow as new material is added.')}<div class="news-grid">${WHATS_NEW.map(n=>`<article><small>${n.date}</small><h3>${n.title}</h3><p>${n.text}</p></article>`).join('')}</div></section>
  <section class="community-strip"><div><div class="eyebrow">COMMUNITY</div><h2>Brainpower beyond the website.</h2><p>Follow new resources on Instagram or join the Discord community.</p></div><div class="hero-actions"><a class="btn light" href="${SITE.instagram}" target="_blank" rel="noopener">Instagram ↗</a><a class="btn outline-light" href="${SITE.discord}" target="_blank" rel="noopener">Discord ↗</a></div></section>`;
}

export function learnPage(){const p=load();return pageHead('LEARN','Interactive VCE Mathematics courses','Short explanations, worked examples, checked questions and topic mastery across Methods and Specialist Mathematics.')+`<section class="section">${sectionTitle('COURSES','Four pathways. One system.','Course content is data-driven, so the same engine scales as more lessons are added.')}<div class="course-grid">${courses.map(c=>courseCard(c,p)).join('')}</div></section><section class="section soft">${sectionTitle('HOW IT WORKS','Learn → practise → test → review')}<div class="feature-grid"><div class="feature card"><span>01</span><h3>Learn</h3><p>Compact explanations and examples rather than walls of notes.</p></div><div class="feature card"><span>02</span><h3>Practise</h3><p>Immediate feedback with Core, VCAA, Advanced and Separator difficulty tags.</p></div><div class="feature card"><span>03</span><h3>Test</h3><p>Move into formal Brainpower assessments with timers and marking schemes.</p></div><div class="feature card"><span>04</span><h3>Review</h3><p>Your dashboard records progress and highlights unfinished topic paths.</p></div></div></section>`}

export function coursePage(id){
  const c=courseById(id); if(!c)return notFoundPage(); const p=load(); const ls=lessonsForCourse(id); const mastery=courseMastery(id,p);
  return pageHead(c.short,c.title,c.desc,`<a class="btn light" href="#practice?course=${c.id}">Practise this course</a>`)+`<section class="section"><div class="course-overview"><aside class="course-summary card"><div class="course-icon large">${c.short.includes('Specialist')?'Σ':'ƒ'}</div><h3>${c.short}</h3>${progressBar(mastery,'Course mastery')}<div class="summary-stat"><b>${ls.length}</b><span>interactive lessons available</span></div><div class="summary-stat"><b>${c.topics.length}</b><span>topic pathways</span></div><a class="btn primary full" href="#lesson/${(ls.find(l=>!p.completedLessons.includes(l.id))||ls[0])?.id}">Continue course →</a></aside><div class="topic-path"><div class="path-intro"><div class="eyebrow dark">COURSE MAP</div><h2>Topic pathways</h2><p>Complete lessons to build mastery. Topics without lessons are already scaffolded and ready for future content.</p></div>${c.topics.map((t,i)=>{const tls=lessonsForTopic(c.id,t.id);const m=topicMastery(c.id,t.id,p);return `<article class="topic-node ${tls.length?'available':'future'}"><div class="topic-number">${t.icon}</div><div class="topic-copy"><small>TOPIC ${String(i+1).padStart(2,'0')}</small><h3>${t.title}</h3>${tls.length?`${progressBar(m)}<div class="lesson-links">${tls.map(l=>`<a href="#lesson/${l.id}" class="lesson-pill ${p.completedLessons.includes(l.id)?'done':''}">${p.completedLessons.includes(l.id)?'✓':'○'} ${l.title}</a>`).join('')}</div>`:`<p>Course shell ready - lesson content to be added.</p>`}</div><div class="topic-count">${tls.length?`${tls.length} lesson${tls.length===1?'':'s'}`:'Coming'}</div></article>`}).join('')}</div></div></section>`;
}

export function lessonPage(id){
  const l=lessonById(id); if(!l)return notFoundPage(); const c=courseById(l.course); const p=load(); const done=p.completedLessons.includes(l.id); const sibling=lessonsForCourse(l.course); const idx=sibling.findIndex(x=>x.id===l.id); const next=sibling[idx+1];
  return pageHead(`${c.short} • ${l.difficulty}`,l.title,l.summary,`<a class="btn light" href="#course/${c.id}">← Course map</a>`)+`<section class="section lesson-section"><div class="lesson-shell"><aside class="lesson-nav card"><div class="eyebrow dark">THIS COURSE</div><h3>${c.short}</h3><div class="lesson-nav-list">${sibling.map(x=>`<a href="#lesson/${x.id}" class="${x.id===l.id?'active':''}">${p.completedLessons.includes(x.id)?'✓':'○'} <span>${x.title}</span></a>`).join('')}</div></aside><article class="lesson-content"><div class="lesson-meta">${tag(l.difficulty,l.difficulty==='Separator'?'danger':'')} ${tag(`${l.minutes} min`)} ${done?tag('Completed','success'):tag(`+${l.xp} XP`)}</div><div class="lesson-block"><div class="block-kicker">CONCEPT</div><h2>${l.title}</h2><p>${renderMathString(l.explanation)}</p><div class="formula-box">${renderMathString(l.formula)}</div></div><div class="lesson-block worked"><div class="block-kicker">WORKED THINKING</div><h3>Build the method</h3><ol>${l.worked.map(s=>`<li>${renderMathString(s)}</li>`).join('')}</ol></div><div class="lesson-block"><div class="block-kicker">YOUR TURN</div><h3>Check your understanding</h3><div class="lesson-questions">${l.questions.map(qid=>questionCard(questionById(qid))).join('')}</div></div><div class="lesson-complete card ${done?'done':''}"><div><div class="block-kicker">LESSON CHECKPOINT</div><h3>${done?'Lesson mastered':'Ready to lock it in?'}</h3><p>${done?'You already earned the completion XP for this lesson.':'Mark the lesson complete when you are happy with the concept and questions.'}</p></div><div class="lesson-end-actions"><button class="btn primary complete-lesson" data-lesson="${l.id}" data-xp="${l.xp}" ${done?'disabled':''}>${done?'✓ Completed':`Complete lesson +${l.xp} XP`}</button>${next?`<a class="btn ghost" href="#lesson/${next.id}">Next lesson →</a>`:`<a class="btn ghost" href="#course/${c.id}">Back to course</a>`}</div></div></article></div></section>`;
}

export function practicePage(params=new URLSearchParams()){
  const focus=params.get('focus')||''; const preset=params.get('course')||'all';
  return pageHead('PRACTICE','Question bank','Filter by course, topic and difficulty. Every question has a predefined answer and worked solution.')+`<section class="section"><div class="filter-panel card"><div class="filter-group"><label for="practice-search">Search</label><input id="practice-search" type="search" placeholder="e.g. integration, vectors…"></div><div class="filter-group"><label for="practice-course">Course</label><select id="practice-course"><option value="all">All courses</option>${courses.map(c=>`<option value="${c.id}" ${preset===c.id?'selected':''}>${c.short}</option>`).join('')}</select></div><div class="filter-group"><label for="practice-topic">Topic</label><select id="practice-topic"><option value="all">All topics</option></select></div><div class="filter-group"><label for="practice-difficulty">Difficulty</label><select id="practice-difficulty"><option value="all">All difficulties</option><option>Core</option><option>VCAA</option><option>Advanced</option><option>Separator</option></select></div><div class="filter-count"><strong id="practice-count">${practiceQuestions.length}</strong><span>questions</span></div></div><div class="practice-grid" id="practice-list" data-focus="${esc(focus)}"></div></section>`;
}

export function testsPage(){return pageHead('TEST CENTRE','Free Brainpower practice tests','Formal assessment material with previews, downloads, timers and score tracking.')+`<section class="section"><div class="filter-panel card"><div class="filter-group grow"><label for="test-search">Search tests</label><input id="test-search" type="search" placeholder="Search by title or topic…"></div><div class="filter-group"><label for="test-course">Course</label><select id="test-course"><option value="all">All courses</option>${courses.map(c=>`<option value="${c.id}">${c.short}</option>`).join('')}</select></div><div class="filter-group"><label for="test-diff">Difficulty</label><select id="test-diff"><option value="all">All difficulties</option><option>Core</option><option>VCAA</option><option>Advanced</option><option>Separator</option></select></div></div><div id="test-list" class="stack">${tests.map(testCard).join('')}</div><div class="coming-card card"><div class="coming-icon">+</div><div><h3>This library is designed to grow.</h3><p>Add a PDF and one metadata object and it can appear here, in The Vault and in global search without rebuilding the interface.</p></div><a class="btn ghost" href="#resources">Open The Vault</a></div></section>`}

export function testPage(id){const t=testById(id);if(!t)return notFoundPage();return pageHead('PRACTICE TEST',t.title,`${t.subject} Units ${t.units} • ${t.topics.join(', ')}`,`<a class="btn light" href="#tests">← All tests</a>`)+`<section class="section"><div class="test-detail-grid"><aside><div class="cover-card card"><img src="${t.thumbnail}" alt="${esc(t.title)} cover"><div class="cover-actions"><a class="btn primary full" href="${t.file}" download>Download test ↓</a><a class="btn ghost full" href="${t.solutionFile}" target="_blank" rel="noopener">Open marking scheme</a></div></div><div class="card test-info"><h3>Assessment details</h3><dl><div><dt>Reading time</dt><dd>${t.reading} min</dd></div><div><dt>Writing time</dt><dd>${t.minutes} min</dd></div><div><dt>Total marks</dt><dd>${t.marks}</dd></div><div><dt>Questions</dt><dd>${t.questions}</dd></div><div><dt>Technology</dt><dd>${t.tech}</dd></div><div><dt>Difficulty</dt><dd>${t.difficulty}</dd></div></dl><button class="btn ghost full bookmark" data-bookmark="test:${t.id}">☆ Save test</button></div></aside><div><div class="card test-description"><div class="eyebrow dark">ABOUT THIS TEST</div><h2>${t.title}</h2><p>${t.description}</p><div class="tagrow">${t.topics.map(x=>tag(x)).join('')} ${tag(t.tech)} ${tag(String(t.year))}</div><a class="btn primary" href="#exam/${t.id}">Start Exam Mode →</a></div><div class="pdf-wrap"><div class="pdf-toolbar"><b>PDF preview</b><a href="${t.file}" target="_blank" rel="noopener">Open in new tab ↗</a></div><iframe class="pdf-frame" src="${t.file}" title="${esc(t.title)} PDF preview"></iframe></div></div></div></section>`}

export function examPage(id){const t=testById(id);if(!t)return notFoundPage();return `<section class="exam-page"><div class="exam-top"><a href="#test/${t.id}" class="exam-back">← Exit Exam Mode</a><div><b>${t.title}</b><span>${t.subject} ${t.units}</span></div><div class="exam-phase" id="exam-phase">READY</div></div><div class="exam-control"><div class="timer-display"><small id="timer-label">Reading + writing time</small><strong id="exam-timer">${t.reading}:${String(0).padStart(2,'0')}</strong><span id="phase-help">Start when you are ready. Reading time will run first.</span></div><div class="exam-buttons"><button class="btn primary" id="exam-start" data-reading="${t.reading}" data-writing="${t.minutes}">Start test</button><button class="btn ghost" id="exam-pause" disabled>Pause</button><button class="btn ghost" id="exam-reset">Reset</button></div><div class="score-entry"><label>Finished? Record your score</label><div class="answer-row"><input id="exam-score" type="number" min="0" max="${t.marks}" placeholder="0-${t.marks}"><button class="btn ghost" id="save-score" data-test="${t.id}" data-max="${t.marks}">Save score</button></div><div id="score-message"></div></div></div><iframe class="exam-pdf" src="${t.file}" title="${esc(t.title)}"></iframe></section>`}

export function resourcesPage(params=new URLSearchParams()){const focus=params.get('focus')||'';return pageHead('THE VAULT','Everything Brainpower publishes','Practice tests, solutions, notes, worksheets and revision resources in one searchable library.')+`<section class="section"><div class="filter-panel card"><div class="filter-group grow"><label for="vault-search">Search resources</label><input id="vault-search" type="search" placeholder="Search the Vault…"></div><div class="filter-group"><label for="vault-type">Type</label><select id="vault-type"><option value="all">All types</option>${[...new Set(resources.map(r=>r.type))].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="filter-group"><label for="vault-course">Course</label><select id="vault-course"><option value="all">All courses</option>${courses.map(c=>`<option value="${c.id}">${c.short}</option>`).join('')}</select></div></div><div class="resource-grid" id="vault-list" data-focus="${esc(focus)}">${resources.map(resourceCard).join('')}</div><div class="vault-note card"><div class="vault-folder">▣</div><div><h3>Built for a large library.</h3><p>The GitHub repository contains organised resource folders and a metadata file. Future PDFs can be added without redesigning this page.</p></div></div></section>`}

export function toolsPage(){return pageHead('TOOLS','Useful study utilities','Small tools that work entirely in the browser - no accounts, API keys or AI.')+`<section class="section"><div class="tool-grid"><article class="tool-card card"><div class="tool-icon">%</div><h3>Percentage calculator</h3><p>Convert any score into a percentage.</p><div class="two-input"><input id="pct-mark" type="number" placeholder="Mark"><input id="pct-total" type="number" placeholder="Total"></div><button class="btn primary" id="pct-calc">Calculate</button><div class="tool-result" id="pct-result">—</div></article><article class="tool-card card"><div class="tool-icon">◎</div><h3>Target score calculator</h3><p>How many marks do you need to reach a target percentage?</p><div class="two-input"><input id="target-percent" type="number" placeholder="Target %"><input id="target-total" type="number" placeholder="Total marks"></div><button class="btn primary" id="target-calc">Calculate</button><div class="tool-result" id="target-result">—</div></article><article class="tool-card card"><div class="tool-icon">θ</div><h3>Exact trig values</h3><p>Select a standard angle.</p><select id="trig-angle"><option value="0">0</option><option value="30">π/6</option><option value="45">π/4</option><option value="60">π/3</option><option value="90">π/2</option></select><div class="trig-result" id="trig-result"></div></article><article class="tool-card card"><div class="tool-icon">?</div><h3>Random practice</h3><p>Skip the filters and jump into a random question.</p><button class="btn primary" id="random-question">Give me a question →</button><div id="random-question-box"></div></article><article class="tool-card card study-timer-card"><div class="tool-icon">◷</div><h3>Study timer</h3><p>A simple 25-minute focus timer.</p><div class="study-clock" id="study-clock">25:00</div><div class="card-actions"><button class="btn primary" id="study-start">Start</button><button class="btn ghost" id="study-reset">Reset</button></div></article><article class="tool-card card"><div class="tool-icon">→</div><h3>Vector visualiser</h3><p>Enter a 2D vector to see its direction and magnitude.</p><div class="two-input"><input id="vec-x" type="number" value="3" aria-label="x component"><input id="vec-y" type="number" value="4" aria-label="y component"></div><button class="btn ghost" id="vector-draw">Draw</button><svg id="vector-svg" viewBox="0 0 240 180" role="img" aria-label="Vector plot"></svg><div id="vector-info" class="mini-result"></div></article></div></section>`}

export function arcadePage(){const p=load();return pageHead('BRAINPOWER ARCADE','Take a break. Keep the brain on.','Optional mini-games with local high scores. None of this affects course mastery.')+`<section class="section"><div class="arcade-grid"><article class="game-card derivative-game"><div class="game-head"><div><div class="eyebrow">DERIVATIVE DASH</div><h2>Differentiate before your lives run out.</h2></div><div class="high-score">Best <b>${p.arcade?.derivativeDash||0}</b></div></div><div class="dash-screen"><div class="dash-stats"><span>Score <b id="dash-score">0</b></span><span>Streak <b id="dash-streak">0</b></span><span>Lives <b id="dash-lives">♥♥♥</b></span></div><div class="dash-question" id="dash-question">Press start</div><div class="dash-input"><input id="dash-answer" placeholder="Derivative" disabled><button class="btn primary" id="dash-submit" disabled>Lock in</button></div><p id="dash-message">Equivalent pre-built answer forms are accepted.</p><button class="btn light" id="dash-start">Start Derivative Dash</button></div></article><article class="game-card bird-game"><div class="game-head"><div><div class="eyebrow">BRAINPOWER BIRD</div><h2>A completely unnecessary academic obstacle course.</h2></div><div class="high-score">Best <b>${p.arcade?.bird||0}</b></div></div><div class="bird-wrap"><canvas id="bird-canvas" width="720" height="360" aria-label="Brainpower Bird game"></canvas><div class="bird-overlay" id="bird-overlay"><h3>Brainpower Bird</h3><p>Avoid SACs, EXAMs and DOMAIN ERROR.</p><button class="btn light" id="bird-start">Start game</button><small>Click/tap the game or press Space to flap.</small></div></div></article></div></section>`}

export function progressPage(){const p=load();const level=levelForXp(p.xp);const nextLevel=level*250;const prev=(level-1)*250;const levelPct=Math.round((p.xp-prev)/(nextLevel-prev)*100);const achievements=[
  ['First Step','Complete your first lesson',p.completedLessons.length>=1],['Getting Serious','Complete 5 lessons',p.completedLessons.length>=5],['Question Machine','Solve 10 unique questions',p.correctQuestions.length>=10],['Separator','Solve a Separator question',p.correctQuestions.some(id=>questionById(id)?.difficulty==='Separator')],['Perfect Test','Record 100% on a test',p.scores.some(s=>s.score===s.max)],['On Fire','Build a 3-day streak',p.streak>=3]
];
return pageHead('PROGRESS','Your Brainpower dashboard','Everything here is stored locally in this browser. No account is required.')+`<section class="section"><div class="profile-banner"><div class="level-orb">${level}</div><div><div class="eyebrow">LEVEL ${level}</div><h2>${p.xp} XP</h2><p>${Math.max(0,nextLevel-p.xp)} XP until Level ${level+1}</p>${progressBar(levelPct)}</div><div class="streak-box"><strong>🔥 ${p.streak}</strong><span>day streak</span></div></div><div class="dashboard-grid"><section><div class="card dashboard-card"><div class="eyebrow dark">COURSE MASTERY</div><h3>Your four pathways</h3>${courses.map(c=>{const m=courseMastery(c.id,p);return `<a class="mastery-row" href="#course/${c.id}"><span>${c.short}</span><div class="mini-progress"><i style="width:${m}%"></i></div><b>${m}%</b></a>`}).join('')}</div><div class="card dashboard-card"><div class="eyebrow dark">ACHIEVEMENTS</div><h3>${achievements.filter(a=>a[2]).length}/${achievements.length} unlocked</h3><div class="achievement-grid">${achievements.map(([name,desc,earned])=>`<div class="achievement ${earned?'earned':''}"><span>${earned?'★':'☆'}</span><div><b>${name}</b><small>${desc}</small></div></div>`).join('')}</div></div></section><aside><div class="card dashboard-card"><div class="eyebrow dark">STATS</div><div class="stat-list"><div><b>${p.completedLessons.length}</b><span>lessons completed</span></div><div><b>${p.correctQuestions.length}</b><span>unique questions solved</span></div><div><b>${Object.values(p.attemptedQuestions||{}).reduce((a,b)=>a+b,0)}</b><span>question attempts</span></div><div><b>${p.bookmarks.length}</b><span>saved resources</span></div></div></div><div class="card dashboard-card"><div class="eyebrow dark">TEST HISTORY</div><h3>Recent scores</h3>${p.scores.length?p.scores.slice(0,5).map(s=>{const t=testById(s.testId);return `<div class="score-row"><div><b>${t?.title||s.testId}</b><small>${fmtDate(s.date)}</small></div><strong>${s.score}/${s.max}<small>${Math.round(s.score/s.max*100)}%</small></strong></div>`}).join(''):`<p class="muted">No test scores recorded yet. Finish an Exam Mode attempt to add one.</p>`}</div><button class="btn danger-outline" id="reset-progress">Reset local progress</button></aside></div></section>`}

export function aboutPage(){return pageHead('BRAINPOWER','About Brainpower Education','A student-focused VCE Mathematics platform combining structured learning, serious practice and free resources.')+`<section class="section"><div class="about-grid"><article class="about-lead"><div class="eyebrow dark">THE IDEA</div><h2>Not another folder full of PDFs.</h2><p>Brainpower is designed as one connected learning system. A student should be able to learn a concept, practise it, sit a formal test, inspect a marking scheme and return to weak areas without jumping between unrelated services.</p><p>The current platform focuses on Mathematical Methods and Specialist Mathematics across Units 1-4, with an architecture that can expand to other subjects later.</p></article><aside class="card principles"><h3>Platform principles</h3><ul class="check-list"><li>Free core resources.</li><li>No AI-generated student content.</li><li>Professional mathematical typesetting.</li><li>Difficulty that extends beyond routine exercises.</li><li>Useful gamification, not distraction.</li><li>Fast static hosting with no required account.</li></ul></aside></div><div class="feature-grid about-features"><div class="feature card"><span>LEARN</span><h3>Interactive courses</h3><p>Methods 1/2, Methods 3/4, Specialist 1/2 and Specialist 3/4.</p></div><div class="feature card"><span>PRACTISE</span><h3>Tagged question bank</h3><p>Core, VCAA, Advanced and Separator questions with worked solutions.</p></div><div class="feature card"><span>TEST</span><h3>Free assessments</h3><p>Preview, download and use Exam Mode for Brainpower tests.</p></div><div class="feature card"><span>PLAY</span><h3>Brainpower Arcade</h3><p>Because a mathematics platform is allowed to have personality.</p></div></div><div class="contact-panel"><div><div class="eyebrow">CONNECT</div><h2>Brainpower community</h2><p>Use Instagram for updates and Discord for the community.</p></div><div class="hero-actions"><a class="btn light" href="${SITE.instagram}" target="_blank" rel="noopener">Instagram ↗</a><a class="btn outline-light" href="${SITE.discord}" target="_blank" rel="noopener">Discord ↗</a></div></div><div class="faq"><h2>FAQ</h2><details><summary>Is the content free?</summary><p>The current platform is designed around freely accessible Brainpower resources. There is no paywall in this build.</p></details><details><summary>Does the site use AI?</summary><p>No. Lessons, questions, answers and resources are pre-built. Interactive checking is deterministic and runs locally in the browser.</p></details><details><summary>Where is progress stored?</summary><p>In the browser's local storage. Clearing browser data will clear local progress unless cloud accounts are added in a future version.</p></details><details><summary>How do I report a mistake?</summary><p>For now, use the Brainpower Instagram or Discord links above. A dedicated issue-reporting backend can be added later.</p></details></div></section>`}

export function searchPage(){return pageHead('SEARCH','Search Brainpower','Search courses, lessons, questions, tests and resources from one place.')+`<section class="section search-section"><div class="search-box"><span>⌕</span><input id="global-search" type="search" autocomplete="off" autofocus placeholder="Try ‘kinematics’, ‘integration’ or ‘vectors’"></div><div id="search-results" class="search-results"><div class="search-hint"><strong>Search the whole platform.</strong><span>Courses • Lessons • Practice • Tests • Resources</span></div></div></section>`}

export function notFoundPage(){return pageHead('404','That page escaped the domain.','The requested Brainpower page could not be found.')+`<section class="section">${emptyState('Nothing here','Return to the homepage and continue from there.','<a class="btn primary" href="#home">Back home</a>')}</section>`}

export function searchResultsMarkup(term){const results=searchEverything(term,tests,resources);if(!term.trim())return `<div class="search-hint"><strong>Search the whole platform.</strong><span>Courses • Lessons • Practice • Tests • Resources</span></div>`;if(!results.length)return emptyState('No matches','Try a broader term such as calculus, Specialist or probability.');return results.map(r=>`<a class="search-result card" href="#${r.go}"><span>${tag(r.type)}</span><div><h3>${r.title}</h3><p>${r.sub}</p></div><b>→</b></a>`).join('')}
